### ISSUE TITLE
Toggling graph lines crashes 

### ISSUE THREAD

**Issue by CommanderRedYT** [OpenDTU-App/opendtu-react-native#12]

**Comment by CommanderRedYT** [comment]
```
11-23 19:39:58.935  4855  4855 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int com.github.mikephil.charting.interfaces.datasets.IDataSet.getEntryIndex(com.github.mikephil.charting.data.Entry)' on a null object reference
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at com.github.mikephil.charting.charts.Chart.drawMarkers(Chart.java:728)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:285)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.draw(View.java:22644)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21519)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.935  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21475)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4421)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4149)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3309)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8653)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:780)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-23 19:39:58.936  4855  4855 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by CommanderRedYT** [comment]
https://github.com/PhilJay/MPAndroidChart/pull/3145#issuecomment-307109432

**Comment by CommanderRedYT** [comment]
Solution: Hide Markers before removing line
